# -*- coding: utf-8 -*-
"""Regressao_linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HteByY4E_MQLyY4zUwAVjV0DPi7v1bNW
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import train_test_split

from google.colab import drive
drive.mount('/content/drive')

csv_file_path = '/content/drive/MyDrive/Salary_dataset.csv'  # Caminho do arquivo na pasta do Drive
df = pd.read_csv(csv_file_path) # Lê o dataset
display(df.head()) #Exibe as 5 primeiras linhas da tabela

# Verificação de elementos faltantes
print(df.isnull().sum())
# Nota: O dataset não possui valores nulos nem variáveis categóricas

# Separação das variáveis
X = df[["YearsExperience"]]  #features
y = df["Salary"]  #target

# Separação em dados de Treino (80%) e Teste (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Criando o modelo de regressão linear
modelo = LinearRegression()

# Treinando o modelo com a base de treino
modelo.fit(X_train, y_train)
print("\nModelo treinado com sucesso!")

# Fazendo previsões usando a base de teste
y_pred = modelo.predict(X_test)

# Calculando a métrica RMSE
# Nota: Usamos root_mean_squared_error diretamente (padrão do scikit-learn moderno)
rmse = root_mean_squared_error(y_test, y_pred)

print(
    f"Coeficiente Angular (Slope/W): {modelo.coef_[0]:.2f}"
)
print(f"Intercepto (Bias/B): {modelo.intercept_:.2f}")
print(f"Métrica RMSE obtida: {rmse:.2f}")

plt.figure(figsize=(8, 6))

# Plotando os pontos reais do conjunto de teste
plt.scatter(X_test, y_test, color="blue", label="Dados Reais (Teste)", s=60)

# Desenhando a reta de regressão gerada pelo modelo
plt.plot(
    X_test,
    y_pred,
    color="red",
    linewidth=2,
    label=f"Reta de Regressão (RMSE: {rmse:.2f})",
)

# Configurações do gráfico
plt.title(
    "Regressão Linear Simples: Anos de Experiência vs Salário", fontsize=14
)
plt.xlabel("Anos de Experiência", fontsize=12)
plt.ylabel("Salário", fontsize=12)
plt.legend()
plt.grid(True, linestyle="--", alpha=0.6)

# Exibindo o gráfico
plt.show()